[package]
name = "bspwm-workspace-icons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bspc-rs = "0.1.1"
xcb = "1.5.0"
regex = "1.11.1"
notify = "7.0.0"
